// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SwimSuite.Data;
using System;

namespace SwimSuite.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn)
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id");
                    b.Property<string>("ConcurrencyStamp").IsConcurrencyToken();
                    b.Property<string>("Name").HasMaxLength(256);
                    b.Property<string>("NormalizedName").HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("\"NormalizedName\" IS NOT NULL");

                    b.ToTable("AspNetRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);
                    b.Property<string>("ClaimType");
                    b.Property<string>("ClaimValue");
                    b.Property<string>("RoleId").IsRequired();

                    b.HasKey("Id");
                    b.HasIndex("RoleId");
                    b.ToTable("AspNetRoleClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id");
                    b.Property<int>("AccessFailedCount");
                    b.Property<string>("ConcurrencyStamp").IsConcurrencyToken();
                    b.Property<string>("Email").HasMaxLength(256);
                    b.Property<bool>("EmailConfirmed");
                    b.Property<bool>("LockoutEnabled");
                    b.Property<DateTimeOffset?>("LockoutEnd");
                    b.Property<string>("NormalizedEmail").HasMaxLength(256);
                    b.Property<string>("NormalizedUserName").HasMaxLength(256);
                    b.Property<string>("PasswordHash");
                    b.Property<string>("PhoneNumber");
                    b.Property<bool>("PhoneNumberConfirmed");
                    b.Property<string>("SecurityStamp");
                    b.Property<bool>("TwoFactorEnabled");
                    b.Property<string>("UserName").HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("\"NormalizedUserName\" IS NOT NULL");

                    b.ToTable("AspNetUsers");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);
                    b.Property<string>("ClaimType");
                    b.Property<string>("ClaimValue");
                    b.Property<string>("UserId").IsRequired();

                    b.HasKey("Id");
                    b.HasIndex("UserId");
                    b.ToTable("AspNetUserClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider").HasMaxLength(128);
                    b.Property<string>("ProviderKey").HasMaxLength(128);
                    b.Property<string>("ProviderDisplayName");
                    b.Property<string>("UserId").IsRequired();

                    b.HasKey("LoginProvider", "ProviderKey");
                    b.HasIndex("UserId");
                    b.ToTable("AspNetUserLogins");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId");
                    b.Property<string>("RoleId");

                    b.HasKey("UserId", "RoleId");
                    b.HasIndex("RoleId");
                    b.ToTable("AspNetUserRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId");
                    b.Property<string>("LoginProvider").HasMaxLength(128);
                    b.Property<string>("Name").HasMaxLength(128);
                    b.Property<string>("Value");

                    b.HasKey("UserId", "LoginProvider", "Name");
                    b.ToTable("AspNetUserTokens");
                });

            modelBuilder.Entity("SwimSuite.Models.Club", b =>
                {
                    b.Property<Guid>("Id");
                    b.Property<string>("Address").HasMaxLength(240);
                    b.Property<DateTime>("CreatedAtUtc");
                    b.Property<string>("Email").HasMaxLength(160);
                    b.Property<string>("Name").IsRequired().HasMaxLength(160);
                    b.Property<string>("PhoneNumber").HasMaxLength(80);
                    b.Property<string>("RegistrationNumber").HasMaxLength(40);

                    b.HasKey("Id");
                    b.ToTable("Clubs");
                });

            modelBuilder.Entity("SwimSuite.Models.TrainingBlock", b =>
                {
                    b.Property<Guid>("Id");
                    b.Property<Guid>("ClubId");
                    b.Property<DateTime>("CreatedAtUtc");
                    b.Property<DateOnly>("Date");
                    b.Property<TimeOnly>("EndTime");
                    b.Property<string>("Location").HasMaxLength(160);
                    b.Property<string>("Notes").HasMaxLength(400);
                    b.Property<TimeOnly>("StartTime");
                    b.Property<Guid>("TrainingGroupId");

                    b.HasKey("Id");
                    b.HasIndex("ClubId");
                    b.HasIndex("TrainingGroupId");
                    b.ToTable("TrainingBlocks");
                });

            modelBuilder.Entity("SwimSuite.Models.TrainingGroup", b =>
                {
                    b.Property<Guid>("Id");
                    b.Property<Guid>("ClubId");
                    b.Property<DateTime>("CreatedAtUtc");
                    b.Property<string>("Description").HasMaxLength(400);
                    b.Property<string>("Name").IsRequired().HasMaxLength(120);

                    b.HasKey("Id");
                    b.HasIndex("ClubId");
                    b.ToTable("TrainingGroups");
                });

            modelBuilder.Entity("SwimSuite.Models.Trainer", b =>
                {
                    b.Property<Guid>("Id");
                    b.Property<Guid>("ClubId");
                    b.Property<DateTime>("CreatedAtUtc");
                    b.Property<string>("Email").HasMaxLength(160);
                    b.Property<string>("FirstName").IsRequired().HasMaxLength(120);
                    b.Property<bool>("IsActive");
                    b.Property<string>("LastName").IsRequired().HasMaxLength(120);
                    b.Property<string>("PhoneNumber").HasMaxLength(80);

                    b.HasKey("Id");
                    b.HasIndex("ClubId");
                    b.ToTable("Trainers");
                });

            modelBuilder.Entity("SwimSuite.Models.TrainerAttendance", b =>
                {
                    b.Property<Guid>("Id");
                    b.Property<Guid>("ClubId");
                    b.Property<DateTime>("CreatedAtUtc");
                    b.Property<bool>("IsPresent");
                    b.Property<string>("Notes").HasMaxLength(400);
                    b.Property<Guid>("TrainerId");
                    b.Property<Guid>("TrainingBlockId");

                    b.HasKey("Id");
                    b.HasIndex("ClubId");
                    b.HasIndex("TrainerId");
                    b.HasIndex("TrainingBlockId", "TrainerId").IsUnique();
                    b.ToTable("TrainerAttendances");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SwimSuite.Models.TrainingBlock", b =>
                {
                    b.HasOne("SwimSuite.Models.Club", "Club")
                        .WithMany("TrainingBlocks")
                        .HasForeignKey("ClubId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SwimSuite.Models.TrainingGroup", "TrainingGroup")
                        .WithMany("TrainingBlocks")
                        .HasForeignKey("TrainingGroupId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Club");
                    b.Navigation("TrainingGroup");
                });

            modelBuilder.Entity("SwimSuite.Models.TrainingGroup", b =>
                {
                    b.HasOne("SwimSuite.Models.Club", "Club")
                        .WithMany("TrainingGroups")
                        .HasForeignKey("ClubId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Club");
                });

            modelBuilder.Entity("SwimSuite.Models.Trainer", b =>
                {
                    b.HasOne("SwimSuite.Models.Club", "Club")
                        .WithMany("Trainers")
                        .HasForeignKey("ClubId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Club");
                });

            modelBuilder.Entity("SwimSuite.Models.TrainerAttendance", b =>
                {
                    b.HasOne("SwimSuite.Models.Club", "Club")
                        .WithMany()
                        .HasForeignKey("ClubId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SwimSuite.Models.Trainer", "Trainer")
                        .WithMany("Attendances")
                        .HasForeignKey("TrainerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SwimSuite.Models.TrainingBlock", "TrainingBlock")
                        .WithMany("TrainerAttendances")
                        .HasForeignKey("TrainingBlockId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Club");
                    b.Navigation("Trainer");
                    b.Navigation("TrainingBlock");
                });

            modelBuilder.Entity("SwimSuite.Models.Club", b =>
                {
                    b.Navigation("Trainers");
                    b.Navigation("TrainingBlocks");
                    b.Navigation("TrainingGroups");
                });

            modelBuilder.Entity("SwimSuite.Models.TrainingGroup", b =>
                {
                    b.Navigation("TrainingBlocks");
                });

            modelBuilder.Entity("SwimSuite.Models.Trainer", b =>
                {
                    b.Navigation("Attendances");
                });

            modelBuilder.Entity("SwimSuite.Models.TrainingBlock", b =>
                {
                    b.Navigation("TrainerAttendances");
                });
#pragma warning restore 612, 618
        }
    }
}
